### ISSUE TITLE
Want to get access token out of instance of SDK

### ISSUE THREAD

**Issue by jbukuts** [spotify/spotify-web-api-ts-sdk#26]
`authenticationStrategy` instance variable is private within the `SpotifyAPI` class

### Expected behavior

Wondering if there was some reason that this [instance variable](https://github.com/spotify/spotify-web-api-ts-sdk/blob/833c1a2858ca4a3312f611f5f665b74ea0e07ca2/src/SpotifyApi.ts#L33) was not exposed. I'd like to be able to access the `getAccessToken` function in order to keep track of one access token when the  `getOAuthToken` runs on token expiration for the [Player SDK](https://developer.spotify.com/documentation/web-playback-sdk/reference#spotifyplayer).

This would be nice given the SDK's ability to refresh tokens automatically through this method as well.

Something like this at the top level:

```ts
public getAccessToken(): Promise<AccessToken> {
    return this.authenticationStrategy.getAccessToken();
}
```

### Actual behavior

Is a private member and not accessible.

### Steps to reproduce the behavior

None

**Comment by sspenst** [comment]
Could update the `needsAuthentication` function in [this PR](https://github.com/spotify/spotify-web-api-ts-sdk/pull/12/files#diff-a15e47d228c48137d932fc42291ec92b34fac7ac17c727fab8bad36a147a6757R147-R150) to the function you mentioned:

```ts
public getAccessToken(): Promise<AccessToken> {
    return this.authenticationStrategy.getAccessToken();
}
```

Would be more generic and should give the data you're looking for.

**Comment by jbukuts** [comment]
> Could update the `needsAuthentication` function in [this PR](https://github.com/spotify/spotify-web-api-ts-sdk/pull/12/files#diff-a15e47d228c48137d932fc42291ec92b34fac7ac17c727fab8bad36a147a6757R147-R150) to the function you mentioned:
> 
> 
> 
> ```ts
> 
> public getAccessToken(): Promise<AccessToken> {
> 
>     return this.authenticationStrategy.getAccessToken();
> 
> }
> 
> ```
> 
> 
> 
> Would be more generic and should give the data you're looking for.

That sounds perfect 👍

**Comment by sspenst** [comment]
I've updated the PR, just need to get @thisisjofrank's approval
