### ISSUE TITLE
Reauthorization happens very often

### ISSUE THREAD

**Issue by Stefterv** [spotify/spotify-web-api-ts-sdk#3]
I think I spoke too soon in my pull request #2 and I'm still running into having to authenticate very often when using the _Authorization Code Flow with PKCE_ method. 

Right now I have to re-auth every few hours, previously when manually requesting a new token with the refresh token on the server that would be much less often. 

Is this an inherent limitation of the auth method? Am I using the library wrong? Or is it a bug?

Normally I would've delved deeper into myself but I figured other people might run into too

**Comment by thisisjofrank** [comment]
Hmmm, that does sound like a bug, I'll do a bit of investigation, sounds like maybe there's an issue with the cashed token. Let me know if you do manage to delve deeper and find anything.

**Comment by Stefterv** [comment]
I just checked and my _spotify-sdk:AuthorizationCodeWithPKCEStrategy:token_ was empty on page load

**Comment by Stefterv** [comment]
It's been fairly painful to replicate as I have to wait an hour every time for the auth token to expire. So far I've repeatedly found run across the first request before the redirect missing the actual Bearer token:
```
....
Accept-Encoding: gzip, deflate, br
Accept-Language: en-NL,en;q=0.9,en-US;q=0.8,nl;q=0.7,de;q=0.6
Authorization: Bearer
Content-Type: application/json
...
```

and thus receiving an 400 error:
```
...
Www-Authenticate: Bearer realm="spotify", error="invalid_request", error_description="Only valid bearer authentication supported"
...
```

**Comment by Stefterv** [comment]
Okay I can trigger it by manually changing the expire key in the localStorage. Right now I've debugged it until [here](https://github.com/spotify/spotify-web-api-ts-sdk/blob/373032c734443396500613ad06d0aee6efec3682/src/caching/GenericCache.ts#L43) The update functions are empty and thus the item is marked as expired and not returned.
