### ISSUE TITLE
Endpoint calls dont support all arguments yet

### ISSUE THREAD

**Issue by 3askaal** [spotify/spotify-web-api-ts-sdk#40]
I'm trying to refactor an app from a community built spotify sdk to this native spotify one. Is it true that some calls are not supporting all arguments your normal endpoints have? I'm trying to control the `time_range` and `limit` of the `topItems()` call for example, but it seems no arguments are allowed yet. Are they still gonna be added?

**Comment by thisisjofrank** [comment]
I've updated the topItems call, please let me know if you find other calls that are missing arguments and I'll fix them up too.

**Comment by 3askaal** [comment]
@thisisjofrank damn thats quick, thanks so much!
