### ISSUE TITLE
React Next environment variables for client ID and redirect URI

### ISSUE THREAD

**Issue by leadbetterben** [spotify/spotify-web-api-ts-sdk#57]
I created a [React project using Next.js](https://react.dev/learn/start-a-new-react-project#nextjs) and then attempted to use this Spotify API similar to the React example in this repository. My code can be seen [here](https://github.com/leadbetterben/removing-art-by-artist/blob/main/src/app/page.tsx) with a key snippet shown below (or through [this link](https://github.com/leadbetterben/removing-art-by-artist/blob/2acaab71931a5ed9c1b0658e4fb8373d2539e4ce/src/app/page.tsx#L7C3-L18C5)):

```
const client_id: string = process.env.SPOTIFY_CLIENT_ID || "error_client_id";
console.log(client_id); // Logs correct client ID

const redirect_uri: string = process.env.SPOTIFY_REDIRECT_URI || "error_redirect_uri";
console.log(redirect_uri); // Logs correct redirect URI

// Giving the client ID and redirect URI as "error" suggesting process.env is empty
const spotifyApi = SpotifyApi.withUserAuthorization(
   client_id,
   redirect_uri,
   Scopes.userDetails
);
```

As the comments suggest, when logging the values of `client_id` and `redirect_uri` I receive the expected values. However, the address when redirected is **https://accounts.spotify.com/authorize?client_id=error_client_id&response_type=code&redirect_uri=error_redirect_uri...** so the values of the client ID and redirect URI from the environment variables are not being passed through.

Does anyone understand why this might be or how I can fix this?

**EDIT:**
I've also done this through the `useSpotify` hook seen in the example, which can be seen in [my branch here](https://github.com/leadbetterben/removing-art-by-artist/blob/use-spotify-hook/src/app/page.tsx).

When I comment out the call to set up the API, I see that the console logs server-side (my console running `npm run dev`) have the correct values but the console logs in the browser's development tools window do not.

**Comment by fruzitent** [comment]
1. Public environment variables in Next.JS must be prefixed with `NEXT_PUBLIC_`.
[Configuring: Environment Variables](https://nextjs.org/docs/pages/building-your-application/configuring/environment-variables#bundling-environment-variables-for-the-browser)

2. Currently, only client-side authentication with PCKE or server-side authentication with a token works. Why it does not save credentials in a mixed workflow is being investigated in the issue below.

Duplicate https://github.com/spotify/spotify-web-api-ts-sdk/issues/47
