### ISSUE TITLE
Can't get the full profile info?

### ISSUE THREAD

**Issue by ZionLG** [spotify/spotify-web-api-ts-sdk#58]
Using the currentuser.profile() I get a "User" type which lacks a lot of the info from the request, I did see in the code that theres a "UserResponse" interface which contains all the data but I cant seem to understand how to get that full data? the token contains the "user-read-private", "user-read-email" scopes

**Comment by fruzitent** [comment]
This function returns the object you expect, but just with the wrong type.
UserResponse was added to https://github.com/spotify/spotify-web-api-ts-sdk/commit/280eaa5d438b50c5cc412333970b9f90f5a5decb and is never used.
A simple cast works as a temporary solution.

```typescript
const profile: UserResponse = (await spotifyApi.currentUser.profile()) as UserResponse
console.log(profile)
```

![image](https://github.com/spotify/spotify-web-api-ts-sdk/assets/40008647/8a180b28-8893-42e9-8b78-f86aee216b26)

There are more mistyped declarations that need to be fixed: https://github.com/spotify/spotify-web-api-ts-sdk/pull/56
