### ISSUE TITLE
Wrong URL param for `additional_types`

### ISSUE THREAD

**Issue by Smirow** [spotify/spotify-web-api-ts-sdk#59]
Should be `additional_types` instead of `additionalTypes` :
https://github.com/spotify/spotify-web-api-ts-sdk/blob/37a0ff77da67d47fe89263840bf8df7f044161f6/src/endpoints/PlayerEndpoints.ts#L11

I can submit a small PR.

**Comment by inferrinizzard** [comment]
Seems to be the case for 
https://github.com/spotify/spotify-web-api-ts-sdk/blob/37a0ff77da67d47fe89263840bf8df7f044161f6/src/endpoints/PlayerEndpoints.ts#L19C12-L19C36
as well
