### ISSUE TITLE
`Track` interface has no `album` property

### ISSUE THREAD

**Issue by Pulau-Komodo** [spotify/spotify-web-api-ts-sdk#7]
The `Track` interface doesn't have an `album` property, despite the API returning one. This necessitates ugly tricks like `(track as any).album` to get the property. The fact this works also demonstrates the property is still there, despite missing from the interface.

**Comment by thisisjofrank** [comment]
Which SDK function were you calling to receive an album without the tracks? 
Different endpoints return different response schemas. 

If you can provide some example code it would help us to debug what is happening here.
